# Generated by Django 5.2.7 on 2026-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(default='/', max_length=512)),
                ('type', models.CharField(choices=[('general', 'General'), ('chat_message', 'Chat Message'), ('chat_read', 'Chat Read Receipt'), ('wishlist_like', 'Wishlist Like'), ('order', 'Order Update'), ('product_new', 'New Product'), ('refund_request', 'Refund Request'), ('refund_update', 'Refund Update')], default='general', max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('endpoint', models.TextField()),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'endpoint')},
            },
        ),
    ]
